<?php

namespace Core\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsRepository extends EntityRepository
{
}