<?php

namespace Core\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ErrorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorsRepository extends EntityRepository
{
}